version: '3.9'
services:
  ecommerce-api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__EcommerceDB=Server=ecommerce-db,1433;Database=EcommerceDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true

